---
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
vector_version: "0.39.0"
vector_config_dir: "/etc/vector"
vector_config:
  sources:
    demo_logs:
      type: demo_logs
      format: syslog
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - demo_logs
      database: logs
      endpoint: demo
      table: vector_table
      compression: gzip
      healthcheck: true
      skip_unknown_fields: true
