---
dependency:
  name: galaxy

driver:
  name: docker
lint:
#  ansible-lint .
#  yamllint .
platforms:
  - name: oraclelinux8
    image: docker.io/pycontribs/oraclelinux:8
    pre_build_image: true

  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true

provisioner:  
  name: ansible

verifier:  
  name: ansible