---
driver:
  name: docker
platforms:
  - name: oraclelinux8
    image: docker.io/library/oraclelinux:8
    pre_build_image: true

  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true