---
- name: Prepare
  hosts: all
  become: true
  tasks:

    - name: Update apt cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install common packages on Ubuntu
      apt:
        name:
          - curl
          - git
          - sudo
          - python3-apt
        state: present
      when: ansible_os_family == "Debian"

    - name: Update yum cache (Oracle Linux)
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install common packages on Oracle Linux
      yum:
        name:
          - curl
          - git
          - sudo
          - python3
        state: present
      when: ansible_os_family == "RedHat"
